<?php

namespace App\Http\Controllers\Api\Menu;

use App\Http\Controllers\Controller;
use App\Models\crud_menu\CrudMenu;
use App\Repositories\Question\QuestionRepository;
use Illuminate\Http\JsonResponse;

class MenuController extends Controller
{
    public function __construct(

    )
    {

    }

    public function getMenu(): JsonResponse
    {
        try {
            $data = CrudMenu::select()
            ->get()
            ->map(function ($item) {
                return [
                    'title' => $item['title'],
                    'url' => $item['url']
                ];
            });

            return $this->success('ok', $data); // TODO: Change the autogenerated stub
        }catch (\Exception $exception){
            return $this->error($exception);
        }
    }
}